# Generated by Django 5.1.5 on 2025-01-29 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('preferred_formation', models.CharField(blank=True, max_length=50, null=True)),
                ('games_won', models.IntegerField(default=0)),
                ('games_drawn', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('expected_points', models.FloatField(default=0.0)),
                ('actual_points', models.FloatField(default=0.0)),
                ('biggest_win', models.CharField(blank=True, max_length=100, null=True)),
                ('biggest_loss', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('year', models.CharField(max_length=9)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='chelsea.competition')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='chelsea.manager')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='chelsea.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'competition', 'year'), name='unique_season_per_player_and_competition')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chelsea.manager')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chelsea.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'manager'), name='unique_vote_per_player_or_manager')],
            },
        ),
    ]
