# Generated by Django 5.1.5 on 2025-02-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chelsea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='trophies_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='aerial_duels_won',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='take_ons',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
